events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl;
        server_name localhost;

        # Ορισμός διαδρομών για τα παραγμένα self-signed πιστοποιητικά
        ssl_certificate /etc/nginx/ssl/localhost.crt;
        ssl_certificate_key /etc/nginx/ssl/localhost.key;

        # (1) Ενεργοποίηση παρωχημένων πρωτοκόλλων (TLSv1 και TLSv1.1)
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

        # (2) Ενεργοποίηση αδύναμων ciphers με υποβάθμιση του Security Level στο 0
        ssl_ciphers 'ECDHE-RSA-AES128-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA:@SECLEVEL=0';
        ssl_prefer_server_ciphers on;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}
